add reconnect to high-level API
LudovicRousseau/pyscard pull request #109
Opened 2021-03-18 10:04 UTC by ElouanPetereau

I added the reconnect method to `CardConnection()` regarding the issue [#107](https://github.com/LudovicRousseau/pyscard/issues/107) that simply make a call to `SCardReconnect()`.

The default mode is `SCARD_SHARE_SHARED` and the default disposition is `SCARD_RESET_CARD` if none as been given and if the connection object doesn't already have one.

I also added a "reconnect" event for the `CardConnectionObserver`.

2021-03-18 18:01 UTC, LudovicRousseau requested changes

2021-03-18 18:01 UTC, LudovicRousseau commented on smartcard/pcsc/PCSCCardConnection.py
> +            if self.disposition == None:
Pourquoi tester si `self.disposition == None` ?
`self.disposition == None` est mis à la bonne valeur dans la méthode `connect()`.

Par contre si j'appele `.reconnect()` *avant* d'appeler `.connect()` ça plante parce que `self.disposition` n'existe pas.

2021-03-19 08:54 UTC, ElouanPetereau commented on smartcard/pcsc/PCSCCardConnection.py
> +        pcscprotocol = translateprotocolmask(protocol)
dfdf

2021-03-19 08:56 UTC, ElouanPetereau commented on smartcard/pcsc/PCSCCardConnection.py
> +            if self.disposition == None:
Le test était fait pour utiliser la dispostion par défaut de reconnect (`SCARD_RESET_CARD`) seulement si aucune disposition n'a été donné dans la méthode `reconnect()` et que la disposition à été changée pour `None`. Le paramètre n'étant pas privé, il est possible de le changer mais vérifier cela n'est peut être pas du ressort du pyscard.

En y réfléchissant je ne suis pas sûr que garder la disposition de self.disposition si aucune n'est donnée en paramètre de `reconnect()` est le bon comportement. Mieux vaut mettre la disposition à celle donnée en paramètre ou à  `SCARD_RESET_CARD` si aucune n'est donnée.
Ce test peut dans ce cas être supprimé.

```suggestion            
```

Par contre je ne testait pas si une connexion à bien été faite avant de pouvoir effectuer une reconnexion donc effectuer un test sur le paramètre self.hcard en début de méthode serait utile
```python
if self.hcard == None:
    raise CardConnectionException('Card not connected')
```

2021-03-19 09:00 UTC, LudovicRousseau commented on smartcard/pcsc/PCSCCardConnection.py
> +            if self.disposition == None:
Peux-tu mettre ton patch à jour avec les corrections STP ?

2021-03-19 10:33 UTC, LudovicRousseau commented
Super.
C'est dans https://github.com/LudovicRousseau/pyscard/commit/a4a030587e316427b1487eb08da2773e478d95fc

2021-03-19 10:33 UTC, closed without merging